version: "3.7"

services:
  consul:
    image: consul
    container_name: consul
    restart: unless-stopped
    network_mode: host
    # volumes:
    #   - consul:/consul/data

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    restart: unless-stopped
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=localhost:8500
    network_mode: host

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    network_mode: host
    # volumes:
    #   - grafana:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    network_mode: host

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    network_mode: host
    volumes:
      - mongo:/data/db

  prometheus:
    build: ./host-prometheus
    container_name: prometheus
    restart: unless-stopped
    network_mode: host
    # volumes:
    #   - prometheus:/prometheus

  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    network_mode: host
    # volumes: 
    #   - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    network_mode: host
    volumes: 
      - redis:/data

  seq:
    image: datalust/seq 
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    network_mode: host
    # volumes: 
    #   - seq:/data

  vault:
    image: vault
    container_name: vault
    restart: unless-stopped
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK
    network_mode: host

volumes:
  # consul:
  #   driver: local
  # grafana:
  #   driver: local
  mongo:
    driver: local
  # prometheus:
  #   driver: local
  # rabbitmq:
  #   driver: local
  redis:
    driver: local
  # seq:
  #   driver: local
  