global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'trill-api-gateway'
    static_configs:
      - targets: ['docker.for.win.localhost:5000']

  - job_name: 'trill-pusher'
    static_configs:
      - targets: ['docker.for.win.localhost:5010']

  - job_name: 'trill-saga'
    static_configs:
      - targets: ['docker.for.win.localhost:5080']

  - job_name: 'trill-ads-service'
    static_configs:
      - targets: ['docker.for.win.localhost:5030']

  - job_name: 'trill-analytics-service'
    static_configs:
      - targets: ['docker.for.win.localhost:5040']

  - job_name: 'trill-stories-service'
    static_configs:
      - targets: ['docker.for.win.localhost:5050']

  - job_name: 'trill-timeline-service'
    static_configs:
      - targets: ['docker.for.win.localhost:5060']

  - job_name: 'trill-users-service'
    static_configs:
      - targets: ['docker.for.win.localhost:5070']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']