global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'trill-api-gateway'
    static_configs:
      - targets: ['trill-api-gateway']

  - job_name: 'trill-pusher'
    static_configs:
      - targets: ['trill-pusher']

  - job_name: 'trill-saga'
    static_configs:
      - targets: ['trill-saga']

  - job_name: 'trill-ads-service'
    static_configs:
      - targets: ['trill-ads-service']

  - job_name: 'trill-analytics-service'
    static_configs:
      - targets: ['trill-analytics-service']

  - job_name: 'trill-timeline-service'
    static_configs:
      - targets: ['trill-timeline-service']

  - job_name: 'trill-stories-service'
    static_configs:
      - targets: ['trill-stories-service']

  - job_name: 'trill-users-service'
    static_configs:
      - targets: ['trill-users-service']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']